port: 4000
auto: true
main_title:  "Matt D. Smith"
description: "A description about my blog homepage."
production_url: mattdsmith.com
markdown: rdiscount
permalink: /:title
pygments: true
rdiscount extensions: [smart]